### PR TITLE
Adding Cisco IOS XR and Cisco NX-OS to Tier 1

### PR DESCRIPTION
**Pull request by edolnx**
As part of our contract close-out with Cisco, I'm adding Cisco IOS XR and Cisco NX-OS to our Tier 1 platform list. They are already available on the site.

### CODE REVIEW

**Comment by mattray** [comment]
:+1: everything is already merged and upstreamed. This is part of Chef's CI/CD

**Comment by coderanger** [comment]
We'll need a LT and at least one maintainer I think, and that has to get added to Chef's MAINTAINERS file.

**Comment by thommay** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
