### PR TITLE
Combine the rationale and description

### PR DESCRIPTION
**Pull request by thommay**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Yes :+1:

**Comment by tyler-ball** [comment]
:+1:

**Comment by coderanger** [comment]
Because yodawg, whats the description and/or rationale for this?

**Comment by jaymzh** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by coderanger** [comment]
Was this discussed somewhere I can't see? We should really be recording the "why" of changes like this for the future. /cc @adamhjk

**Comment by thommay** [comment]
Sorry, I didn't realise you were asking a question. 
Because most of the time the description is the rationale, and even when it's not you want to read the rationale before the specification.

**Pull request merged**
