### PR TITLE
Auto-vivify plugin configuration hashes.

### PR DESCRIPTION
**Pull request by mcquin**
We can auto-vivify hashes easily, without using `method_missing`. This change proposes auto-vivifying plugin configuration hashes at all levels, instead of only at the plugin-name level. This also simplifies enforcing Symbol-only keys and look up.

\cc @lamont-granquist @danielsdeleo @jkeiser @coderanger @btm

### CODE REVIEW

**Comment by coderanger** [comment]
This would break anything that checks for a key via code like `if config[:foo]` since accessing the key creates and stores it. `include?` should still work, but can you perhaps including some motivation for this change?

**Comment by lamont-granquist** [comment]
The problem is allowing `Ohai[:plugin][:dmi]` to autovivify to a hash without the user having to create it which seems to be necessary and required by the RFC, while blocking `Ohai[:plugin][:dmi][:foo][:bar]` from autovivifying would additionally require an autovivifying Hash that stopped after 2 levels.

That's clearly awful code and UX, so it should either be all or nothing, so the autovivifying of the top levels is driving making the whole thing autovivify.

Unless there's a way to create and prepopulate the top level hashes without autovivifying?  I didn't look at the code, but that would be the way to eliminate all autovivification....

**Comment by mcquin** [comment]
As far as I can tell, we'll already have to auto-vivify the hash at the plugin-name level. 

```ruby
config_context :ohai do
  default :plugin, {}
end
```

```
pry> ohai.plugin[:foo][:bar] = :baz
NoMethodError: undefined method `[]=' for nil:NilClass
```

If we choose to only auto-vivify at the plugin-name level, we still have the issue of `if Ohai.config[:plugin][:foo]` instantiating the `:foo` key to a new Hash. We could do something gross and modify `[](key)` such that if `{}` then return `nil`, or handle that in a DSL method. I was going to need to likely create a subclass of `Hash` and override `[]=(key, value)` to enforce the keys-as-Symbols rule anyway.

**Comment by coderanger** [comment]
If we did something like `config[:plugin] = Hash.new {|k, h| h[k] = Hash.new}` you get the behavior that `config[:plugin][:dmi]` vivifies and is a hash, but `config[:plugin][:dmi][:foo]` would be nil if unset.

**Comment by mcquin** [comment]
Okay. That's fair.

**Comment by lamont-granquist** [comment]
Guess that works out okay.

**Pull request closed without merging**
