### PR TITLE
Add Self Documenting Resources RFC

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by coderanger** [comment]
If we aren't going to go with YARD-style markup, we should say why :)

**Comment by coderanger** [comment]
Also would like to see some API examples for how to use this data either inside Chef itself or other tools, and possibly a proposed JSON schema for how we might store it.

**Comment by thommay** [comment]
We approved this @chef/rfc-editors

**Comment by thommay** [comment]
thanks @adamleff

**Pull request merged**
