### PR TITLE
Add fb prefix for Supermarket.

### PR DESCRIPTION
**Pull request by jaymzh**

### CODE REVIEW

**Comment by thommay** [comment]
👍

**Comment by lamont-granquist** [comment]
👍

**Comment by jaymzh** [comment]
(just FYI, this is one of the repos I don't have commit on, so don't wait for me to merge :)

**Comment by thommay** [comment]
@robbkidd can you rub some supermarket love on this ticket?

**Comment by jaymzh** [comment]
I'm not in a rush by any means.... I just know that people generally wait on me to merge FB diffs in other repos and didn't want that to happen here.

**Comment by coderanger** [comment]
Confirmed nothing on Supermarket using this prefix.

**Comment by robbkidd** [comment]
👍  Confirmed @coderanger's confirmation. You have clearance, Clarence.

**Pull request merged**
