### PR TITLE
add Ubuntu 16.04

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by ranjib** [comment]
:+1: 
change title to drop 12.04

**Comment by lamont-granquist** [comment]
lol, good catch

**Comment by coderanger** [comment]
12.04 is still supported for another year so by appendix 1 this is incorrect.

**Comment by schisamo** [comment]
Just to reiterate what @coderanger said, we will be building and testing on Ubuntu 12.04 until at least April 2017 per the Ubuntu LTS support schedule.

**Comment by lamont-granquist** [comment]
fair 'nuff

**Comment by coderanger** [comment]
👍

**Comment by johnbellone** [comment]
FWIW we've been using ChefDK and Chef Client with 16.04 without issue.

**Comment by lamont-granquist** [comment]
yeah, there's not much reason it wouldn't work, but we should still make the statement that we support it

**Comment by thommay** [comment]
👍

**Comment by schisamo** [comment]
👍

**Comment by schisamo** [comment]
@lamont-granquist Can you also correct the phrase:

> "Omnitruck" (full-stack installer) packages

to the proper:

> "Omnibus" (full-stack installer) packages

I have no clue what an Omnitruck package is.

**Comment by jjasghar** [comment]
🚀 👍 🚀

**Comment by nathenharvey** [comment]
On hold pending clarification of "support" (#204).

**Comment by ccope** [comment]
Is this still blocked? Looks like the linked issue is closed.

**Comment by lamont-granquist** [comment]
16.04 was added here (with an asterix):  https://docs.chef.io/platforms.html

we don't track specific versions in this document any more.

**Comment by sanmansabane0** [comment]
As I understand everything is supported as I am going to install Chef on Ubuntu 16.04, because it is not listed to support for Ubuntu 16.04 on the [download page](https://downloads.chef.io/chef-dk/ubuntu/)

**Pull request closed without merging**
