### PR TITLE
Reopen RFC 28, Mailing List Migration

### PR DESCRIPTION
**Pull request by nathenharvey**
Migrating to Google Groups failed
Suggest migrating to Discourse

### CODE REVIEW

**Comment by coderanger** [comment]
Should probably add a note about what failed with Groups.

**Comment by jaymzh** [comment]
indeed. and how interaction looks via email for the more rich things people can do in discourse which is going to be a deal breaker for a large portion of the community.

**Comment by nathenharvey** [comment]
I've updated the RFC with some more info on discourse and why the migration to Google Groups failed.

**Comment by adamhjk** [comment]
By the power vested in me by having written Chef in the first place, and continuing to not be an asshole, I approve this RFC. Take it away, @chef/rfc-editors

**Pull request merged**
