### PR TITLE
Ohai cloud network enhancements

### PR DESCRIPTION
**Pull request by mattray**
Proposed updates to the network plugin to handle networks not named 'public' or 'private'.

### CODE REVIEW

**Comment by nathenharvey** [comment]
This PR is currently on the [agenda for our next IRC developers' meeting](https://github.com/chef/chef-community-irc-meetings/blob/master/2015-03-19-agenda.md).

Please let me know if it gets merged or otherwise closed before then so that the agenda can be updated.

Thanks!

**Comment by nathenharvey** [comment]
@mattray can you please add the appropriate copyright notice to this RFC before our meeting tomorrow?

    ## Copyright

    This work is in the public domain. In jurisdictions that do not allow for this,
    this work is available under CC0. To the extent possible under law, the person
    who associated CC0 with this work has waived all copyright and related or
    neighboring rights to this work.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Comment by jonlives** [comment]
@chef/rfc-editors this is approved for merge once @mattray removes the line regarding Ohai 8

**Comment by ranjib** [comment]
:+1:

**Comment by btm** [comment]
:+1: given no breaking changes which I incorrectly inferred from the note about Ohai 8.

**Comment by martinb3** [comment]
:+1: we end up using [something similar](https://github.com/chef/ohai/blob/master/lib/ohai/plugins/rackspace.rb#L101-L121) for `node['rackspace']['private_networks'][0...i]['label']` from the Rackspace Ohai data. It would be useful to have it across all cloud providers so we could write more reusable library cookbooks that supported labelled interfaces.

**Comment by caryp** [comment]
nice!

**Comment by mattray** [comment]
@chef/rfc-editors @jonlives @btm requested change made.

**Comment by btm** [comment]
We acknowledge the change was made at today's IRC meeting :).

We will merge this.

**Comment by btm** [comment]
rebased into d07816713624ede1097105e028ddf24f61e7de36, merged into master and accepted as RFC046.

**Pull request closed without merging**
