### PR TITLE
First pass on resource deprecation RFC

### PR DESCRIPTION
**Pull request by coderanger**
I think we should remove `deploy`, `http_request`, and `erl_call` from Chef. Discuss.

### CODE REVIEW

**Comment by tas50** [comment]
Http_request is pretty heavily used on supermarket

**Comment by coderanger** [comment]
@tas50 What's the use case?

**Comment by lamont-granquist** [comment]
yeah mostly people want feature requests and extensions to http_request, not removing it...

**Comment by stevendanna** [comment]
👍 on `erl_call`.  It is kinda a silly resource.

I think that if we are going to move these out into cookbooks, it would probably good to have a plan for the life of the cookbook.  Moving them to a cookbook means we still maintain them, so it seems to me that the main benefit is preventing users from seeing confusing/ill-advised resources in core chef.  That goal can probably also be solved in documentation without any deprecation.

That said, I *am* in favor of deprecating the deploy resource on some timeline.  My worry there is doing that before we have other primitives in core chef to facilitate replacing it.

**Comment by iennae** [comment]
I thought step one was to write up the model of deprecation. Then based on that we could align which resources to deprecate. 

The erl_call resource based on the definition we discussed at Chef Summit sounds like the svn resource we discussed as an example. If there is not user confusion or maintenance burden and it helps even a small number of people what is the reason to deprecate?

From the notes that Seth wrote on the board I have:

- primitive versus compound resources
- broken for N days
- disconnect from user expectation
- % of supported platforms
- footgun-ness for new user

**Comment by coderanger** [comment]
@iennae That is certainly an option, but I don't think it would be a productive one given that all three of these are IMO candidates for removal from core for different reasons that have little to do with each other.

**Comment by iennae** [comment]
That's kind of my point. I'm not saying every resource has to have the same reason, but it'd be nice to be clear and specific about the reasoning with something to map back to for the rest of the resources that might be brought up.

**Comment by jaymzh** [comment]
I'm with @iennae - We should start with some basic guidelines for when, why and how we remove things from core. It does not need to be an exhaustive list, but when I mentioned in the meeting an RFC, it was for getting some documentation around "valid" reasons we might want to do that as well as documenting the process for doing so...

**Comment by coderanger** [comment]
@iennae I don't think there is any such clear reason here though, all three are IMO candidates for totally unrelated reasons. That said, if someone wants to make a process I'm happy to go that route too, I just don't really want to wait on it.

**Comment by thommay** [comment]
I'm happy with the removal of `erl_call` since it's bonkers and probably no-one has used it since couch died. I'm happy with the removal of `deploy` to a cookbook, since it's complex, hugely tied to very specific rails/cap workflows and more or less unmaintained.
I think we can't remove `http_request`, but we can make it clearer how it's used, what it's good for, and how to make http requests and use the data from them in Chef.

**Comment by thommay** [comment]
@iennae please can you write up an RFC that captures that deprecation model?

**Comment by iennae** [comment]
@thommay I could take a stab at a first draft of it :)

**Comment by thommay** [comment]
Approved, take it away @chef/rfc-editors

**Comment by adamleff** [comment]
RFC 98 assigned, merged to master in f45eb1d6

**Pull request closed without merging**
