### PR TITLE
XML file editing as a first class resource

### PR DESCRIPTION
**Pull request by ranjib**
Enables user to inject values in an XML file based on XSLT mappings

### CODE REVIEW

**Comment by coderanger** [comment]
Why should this be in core instead of a cookbook/gem?

**Comment by ranjib** [comment]
because we encounter this quiet frequently, currently we use it as an lwrp only. But i think this has wide enough use case that we can consider having this in core.

**Comment by coderanger** [comment]
If it is mostly with Java-y things, maybe include it in the java cookbook?

**Comment by coderanger** [comment]
Or more likely, in its own cookbook that is a dependency of java.

**Comment by ranjib** [comment]
there are several non-java apps (ossec for example). We can write those cookbooks or those cookbooks can offer much better lwrps if this resource is in core.

**Comment by coderanger** [comment]
I don't see why it would be a better LWRP if it is in core, the code is the same regardless of how it is packaged.

**Comment by lamont-granquist** [comment]
Depends on nokogiri, presumably?  So this would effectively write a check on our time for getting nokogiri installing on EL5 and AIX and Solaris 10?

**Comment by ranjib** [comment]
@lamont-granquist yeah, i was thinking of implementing it using nokogiri. :-( . i guess it will be difficult then

**Comment by lamont-granquist** [comment]
Yeah, I suspect there is zero time to port nokogiri to AIX in the next 6 months at least.

**Comment by erichelgeson** [comment]
There is a cookbook that does something similar - https://supermarket.chef.io/cookbooks/xmledit

**Comment by jonlives** [comment]
I'm not super in favour of this being in Core, I agree with @coderanger that it'd probably be better off in a cookbook as an *WRP.

**Comment by lamont-granquist** [comment]
To reiterate the IRC discussion, would like to see this as a cookbook first, and using rexml.

I'd also like to see a bit of higher level design to as we head down this road as to how json and yaml and ini all fit into this in addition to xml.   I really don't want to see the organic growth which led to the confusion over all the different file/template/cookbook_file/remote_file resources and their confusing names.

**Comment by coderanger** [comment]
Also a minor request, if this is going to be built for delta editing, can we call it `xml_edit`?

**Comment by ranjib** [comment]
Following is the first cut for an REXML based HWRP
https://github.com/GoatOS/xml_file

**Comment by ranjib** [comment]
I'm closing this. I have implemented a REXML based HWRP prototype as discussed in the IRC, and i'll be using it. But given no one else has upvoted this, and consuming the HWRP from cookbook is a decent workaround, im closing this. I'll be happy to reopen this if others show any interest.

**Comment by juliandunn** [comment]
I think that's sufficient for now; thanks for the cookbook/HWRP @ranjib

**Pull request closed without merging**
