### PR TITLE
Robust Attribute Tracing Support

### PR DESCRIPTION
**Pull request by clintoncwolfe**

### CODE REVIEW

**Comment by nathenharvey** [comment]
should we close this for now and revisit after [Attributes API 2](https://github.com/chef/chef-rfc/pull/77) is done?

**Comment by lamont-granquist** [comment]
yeah, we also need Attributes Core 2 as well

**Comment by clintoncwolfe** [comment]
WFM

**Comment by nathenharvey** [comment]
Closing for now.  Will revisit or incorporate into the new attributes work that's being proposed.

**Comment by vinyar** [comment]
:+1: for whenever this gets reopened

**Comment by odcinek** [comment]
:+1: on this, would be great to revive https://github.com/chef/chef/pull/1373

**Comment by lamont-granquist** [comment]
I need to ship the node attributes re-write when I get back off of vacation.  Attribute tracing should get easier after I do that.

**Pull request closed without merging**
