### PR TITLE
Generate GitHub pages for RFC

### PR DESCRIPTION
**Pull request by thommay**

### CODE REVIEW

**Comment by jjasghar** [comment]
:metal: great idea.

**Comment by coderanger** [comment]
For anyone that wants to see the output https://chef.github.io/chef-rfc/ 👍

**Comment by coderanger** [comment]
@thommay Would it be possible to parse out the first `<h1>` from the markdown as a title if one isn't given explicitly?

**Comment by ranjib** [comment]
:+1: 
Its hard to tell which of the RFCs are done. If state is "final" does that mean the RFC is done? If so, I'll go ahead and update couple of them at least

**Comment by thommay** [comment]
@ranjib yeah, not sure what the right answer is there.

@coderanger it's annoying to do, and I'd rather make someone do an extra line of work than rely on something fragile :)

**Comment by nathenharvey** [comment]
👍  I will add this to future agendas

**Pull request merged**
