### PR TITLE
Chef code should have consistent style

### PR DESCRIPTION
**Pull request by thommay**
Please let's not discuss the actual checks we want to disable here,
but rather let's just discuss having such a thing *at all* and then use the chef/chefstyle repo to define a set of checks that we want.

cc @chef/engineering-services

### CODE REVIEW

**Comment by jaymzh** [comment]
OMG yes.

:+1: 
:+1: 
:100:

**Comment by patrick-wright** [comment]
Great idea.

**Comment by coderanger** [comment]
Not sure how implicit we want to leave this, but some Chef-owned repos should probably be excepted. Like Supermarket, Rails code generally has very very different style than anything else.

**Comment by lamont-granquist** [comment]
Not a repo.   Like chef-config have another gem we ship out of chef/chef and is tied to the chef version.

**Comment by thommay** [comment]
@lamont-granquist I'm not sure I like that. We should release and version chefstyle appropriately but I think tying it to the chef repo just adds noise to chef PRs and is slightly more awkward to work with in other repos.

**Comment by lamont-granquist** [comment]
And we really need to be clear here that this is going to be a gem which will target chef/chef and pretty much only chef/chef (and maybe the related mixlib's) and will not be architected to the needs of cookbook authors at all, and is not intended as a general purpose ruby style guide for the chef community at large.

That is because some issues only come up in chef/chef (like rescue Exception being perfectly acceptable if you're decorating the exception and re-raising it), and because some issues may be large yak shaves to fix correctly in the chef/chef codebase (thinking about the `File.exists?` to `File.exist?` PR that got lost somewhere in the bowels of FileAccessControl and died)

**Comment by lamont-granquist** [comment]
Think I just answered your ninja post there.  We need to target chef/chef's needs specifically, and that will be the really hard part, so I think it lives in the chef/chef repo.

**Comment by thommay** [comment]
@coderanger i kinda felt that rails projects could be additive over the top, but I'm easy.

**Comment by thommay** [comment]
well, but it should be targetting chef, chef-zero, ohai, cheffish, mixlib-* at least.

**Comment by coderanger** [comment]
It sounds like we need to first decide if this is for chef/chef only, most Chef Software projects, or "the community". If we end up with 2 we can talk about which projects to use it on.

**Comment by lamont-granquist** [comment]
I am 1,000,000% against having a single ruleset for everyone plus chef/chef, and I'm positive that way will end up in endless bikesheds, yak shaves and tears.

**Comment by damacus** [comment]
👍 for consistency across repos.

Makes it much easier to teach new comers if styling is consistent with
"current"  practise (whatever we chose at the time).

**Comment by thommay** [comment]
I made some changes to try and clarify @lamont-granquist's concerns and ensure that rules are added in  a pretty conservative manner.

**Comment by lamont-granquist** [comment]
I think we need to tackle chef/chef first and that will be the hard problem.  I think ohai and the mixlib's come along for the ride.  I doubt we'll hit anything in those repos that we don't hit in core chef.

**Comment by coderanger** [comment]
Using chef/chef to figure out which cops to enable seems like a reasonable plan, but then expect to enable it for other repos after that "training wheels" stage?

**Comment by lamont-granquist** [comment]
Yeah once we've applied stuff to chef/chef then it should be straightforward to apply it to all the other repos.

**Comment by schisamo** [comment]
Do we envision chefstyle supporting multiple rulesets in the future? This PR is obviously discussing the Ruby project-specific ruleset. We could also ship a ruleset aimed at cookbooks and cookbook authors. Or is the intention to have a completely different gem?

**Comment by lamont-granquist** [comment]
I'd really like to have a completely separate gem to keep the bikesheds segregated.

**Comment by thommay** [comment]
@schisamo completely separate gem

**Comment by btm** [comment]
:+1: congrats on pre-bikeshed foundation-shedding.

**Comment by adamhjk** [comment]
I am the decider, and I approve this rfc. Go for it, @chef/rfc-editors

**Pull request merged**
