### PR TITLE
mixlib-config 3 RFC

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by nathenharvey** [comment]
This PR is currently on the [agenda for our next IRC developers' meeting](https://github.com/chef/chef-community-irc-meetings/blob/master/2015-03-19-agenda.md).

It's currently in the Backlog Clean-up section of the agenda though.  Should it be moved up as a PR that we actually review?

Thanks!

**Comment by nathenharvey** [comment]
@jkeiser can you please add the appropriate copyright notice to this RFC before our meeting tomorrow?

    ## Copyright

    This work is in the public domain. In jurisdictions that do not allow for this,
    this work is available under CC0. To the extent possible under law, the person
    who associated CC0 with this work has waived all copyright and related or
    neighboring rights to this work.

**Comment by lamont-granquist** [comment]
I'm not wild about the exact API in this one since it smells like method_missing

**Comment by jkeiser** [comment]
I'm withdrawing this for the moment; I feel the regexes go too far, and I have an increasing suspicion that we should use resources for config specifications (or at least something with similar syntax).

**Pull request closed without merging**
