### PR TITLE
platform addition/removal addendum

### PR DESCRIPTION
**Pull request by mattray**
It would be useful to provide a timeline for the addition and deletion of Tier 1 and 2 platforms.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1: goodbye solaris 9...

**Comment by jamescott** [comment]
+1

**Comment by charlesjohnson** [comment]
+1

**Comment by juliandunn** [comment]
:+1: 

Let's make sure we update the platforms doc in chef-docs @jamescott

**Comment by adamhjk** [comment]
I am the decider, and I approve this message. /cc @chef/rfc-editors

**Pull request merged**
