### PR TITLE
RFC for Azure Chef Extension cmdlet

### PR DESCRIPTION
**Pull request by muktaa**

### CODE REVIEW

**Comment by thommay** [comment]
I'm not sure this needs to be an RFC. Given the age of this PR, can we just close it, and do any necessary work (assuming there's any left) as a PR for knife-azure?

**Comment by muktaa** [comment]
Closing the PR..

**Comment by jkeiser** [comment]
Um, I don't know how that happened.  huboard / waffle perhaps?

**Comment by muktaa** [comment]
@nimishas - fyi

**Pull request closed without merging**
