### PR TITLE
Test Kitchen Multi-Server Testing

### PR DESCRIPTION
**Pull request by coderanger**
Okay so remember how I said last time that I would stop writing new RFCs that I don't have the bandwidth to implement? Well I lied. But I think this is worth writing down at least so we can start talking about something concrete.

This has been on the Test Kitchen to-do list for _years_ now. I think this design should cover all the use cases I've seen or heard of in the many many times this has been discussed at Summits, meetups, the mailing list, Slack, and probably plenty of other places.

I still really don't like the name `supersuites` but I'm purposefully leaving the terrible name there for now so people will suggest better ones. So far the suggestions I've seen: `multisuite`, `multi`, and `group`. There are also a bunch of `[ed:]` questions in the text, if you have opinions on any or all of them please leave line comments on them.

This is probably going to be a hell of a climb to implement all of it no matter how we do it, but every journey starts with a single step 👣

### CODE REVIEW

**Comment by brandocorp** [comment]
`integrations` or `plans` might be good alternatives to the `supersuite`

**Comment by cheeseplus** [comment]
`integration` as a term is already a bit loaded in the context of kitchen folder structure for tests. `plan` is a bit better but also don't want to folks to confuse with habitat.sh's plan.sh.

Naming things is still super hard but keep the comments and suggestions coming!

**Comment by coderanger** [comment]
`plan` is probably the best I've heard so far. The overlap with Habitat is bad, but not the worst thing ever.

**Comment by shortdudey123** [comment]
- `suite_plan`
- `test_plan`

(with or without `_`)

**Comment by thommay** [comment]
Decided and approved. @chef/rfc-editors take it away!

**Comment by coderanger** [comment]
To capture from the meeting, I will deal with picking a better name when I or someone else gets the cycles to implement this. Until then at least we have a plan on record and can use this for at least vague estimation on how long it will take.

**Comment by adamleff** [comment]
Merged in 07f809d - thanks!

**Pull request closed without merging**
