### PR TITLE
Rfc001 chef extension support in knife azure

### PR DESCRIPTION
**Pull request by kaustubh-d**
[WIP]

RFC to design the changes to knife azure for adding/updating azure chef extension.

### CODE REVIEW

**Comment by thommay** [comment]
It's not clear to me that this should be an RFC, rather than just a PR against knife-azure.

**Comment by nathenharvey** [comment]
This PR is currently on the [agenda for our next IRC developers' meeting](https://github.com/chef/chef-community-irc-meetings/blob/master/2015-03-19-agenda.md).

Please let me know if it gets merged or otherwise closed before then so that the agenda can be updated.

Thanks!

**Comment by nathenharvey** [comment]
@adamedx do you have thoughts on @thommay's suggestion that this should just be closed and managed as a PR, not an RFC?

**Comment by adamedx** [comment]
I'm just going to close because this is actually talking about a separate project, not the Chef project.

**Pull request closed without merging**
