### PR TITLE
The mailing list migration is complete

### PR DESCRIPTION
**Pull request by nathenharvey**

### CODE REVIEW

**Comment by coderanger** [comment]
In theory final is only used for standards track but seems fine either way, what say the other @chef/rfc-editors?

**Comment by nathenharvey** [comment]
Is there something other than "Final" such as "Completed" or "Implemented"?  

"Accepted" feels to me like the idea has been accepted but I don't know how to indicate that the work has been completed.

**Comment by thommay** [comment]
Final feels a bit wrong for an informational RFC but I'm not sure it's worth the bikeshed of coming up with something else :)

**Comment by adamleff** [comment]
I think "Final" doesn't appropriate represent what we're trying to convey, but I'm with @thommay that a bikeshed on what it SHOULD be might not be worthwhile :)

I'd like to propose we simply add a "Note: The mailing list migration was completed on Month Day, Year." right after the metadata table and leave it as Accepted.

**Comment by nathenharvey** [comment]
great idea, @adamleff.  I've reset the status and added a note about the cutover date.

**Comment by adamleff** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Comment by btm** [comment]
This was approved by @adamedx as the decider in the [2015-11-12](https://github.com/chef/chef-community-irc-meetings/blob/master/2015/2015-11-12/2015-11-12-minutes.md) meeting.

**Pull request merged**
