### PR TITLE
Jk/in parallel

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by thommay** [comment]
@adamhjk @jkeiser any reason we can't get this merged tomorrow?

**Comment by thommay** [comment]
:+1:

**Comment by jkeiser** [comment]
I won't be here until next week :)

**Comment by nathenharvey** [comment]
This PR is currently on the [agenda for our next IRC developers' meeting](https://github.com/chef/chef-community-irc-meetings/blob/master/2015-03-19-agenda.md).

Please let me know if it gets merged or otherwise closed before then so that the agenda can be updated.

Thanks!

**Comment by nathenharvey** [comment]
@jkeiser can you please add the appropriate copyright notice to this RFC before our meeting tomorrow?

    ## Copyright

    This work is in the public domain. In jurisdictions that do not allow for this,
    this work is available under CC0. To the extent possible under law, the person
    who associated CC0 with this work has waived all copyright and related or
    neighboring rights to this work.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by jonlives** [comment]
Once @jkeiser has added a clarification that "future things" will req

**Comment by btm** [comment]
Squashed and merged in 5e13978d3d7214f532b455e1a2e9f8866f54126b. This was accepted as RFC044.

**Pull request closed without merging**
