### PR TITLE
Create RFC template for easy copying

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by ranjib** [comment]
:+1:

**Comment by coderanger** [comment]
We should just make sure to update this in sync with RFC 0 as needed. There has only been two changes to that template so far though, so that seems entirely manageable. :+1:

**Comment by coderanger** [comment]
(as this is a purely procedural thing and not new content, we can probably merge with 2 +1s from the editors team /cc @chef/rfc-editors)

**Comment by ranjib** [comment]
i think we should add reference of this template on rfc#000

**Comment by jonlives** [comment]
:+1: - as that's 2 +1s, gonna merge this.

**Pull request merged**
