### PR TITLE
Add RFC for order of operations in compound actions with inline resources

### PR DESCRIPTION
**Pull request by jkeiser**
…rces

### CODE REVIEW

**Comment by coderanger** [comment]
:+1: Definitely the way it should work.

**Comment by lamont-granquist** [comment]
:+1: surprised me that it wasn't this way already.

**Comment by thommay** [comment]
good grief, yes. :+1:

**Comment by stevendanna** [comment]
holy moly. :+1:

**Comment by jeffbyrnes** [comment]
Yes please :+1:

**Comment by jonlives** [comment]
:+1:

**Comment by thommay** [comment]
Approved! Make it so, @chef/rfc-editors

**Pull request closed without merging**
