### PR TITLE
Supermarket cookbook testing indicator

### PR DESCRIPTION
**Pull request by martinisoft**
Im proposing this RFC in an effort to help educate and inform the community about cookbook testing and hopefully improving overall quality of publicly consumed cookbooks. For several years now I've personally wanted an easy way for open source cookbooks to leverage continuous integration systems and add testing to existing cookbooks. It is a hard problem to solve, however. I feel we need to start somewhere and help welcome new and existing Chef users into the community while fostering good practices when it comes to testing.

Looking for feedback on the overall vision while trying not to get into the weeds of implementation specifics. I personally promise to work directly with the Chef Supermarket and ChefDK teams in order to help implement these proposed changes. 

As a major consumer of the community cookbooks out there and contributor to them, this is a wish I've had for a very long time.

### CODE REVIEW

**Comment by damacus** [comment]
Thinking about differing levels of checks:
- Does the repo have a `.travis.yml` or `appveyor.yml`?
-

**Comment by damacus** [comment]
Thinking about differing levels of checks:
- Does the repo have a `.travis.yml` or `appveyor.yml`?
- What's the status of the build (for this version of the coobook?

If we want to do a true "does this cookbook work on my platform"? Then we'll need to wire up `supported_platforms` to a badge in supermarket. 

As an aside, it'd be nice to pull the `supports 'windows'/'ubuntu'` into a badge or something a bit more visually impactful.

**Comment by nathenharvey** [comment]
The Supermarket currently renders the markdown in a cookbook's `README.md`.  Adding build status indicators is easily done there by connecting your cookbook to a build service that allows for status indicators.

As an example, the [httpd cookbook] (https://supermarket.chef.io/cookbooks/httpd) has a status indicator that shows the current build is passing and links off to the [travis page showing results](https://travis-ci.org/chef-cookbooks/httpd).

That same cookbook also displays a cookbook version indicator.

The code in the `README.md` looks like this:

`[Build Status](https://travis-ci.org/chef-cookbooks/httpd) [Cookbook Version](https://supermarket.chef.io/cookbooks/httpd)`

The Supermarket displays these badges on the main cookbook page.

httpd_cookbook_-_chef_supermarket

Does this meet your criteria?

It provides a lot of flexibility to the cookbook maintainers. 

Perhaps the thing we should do is be more prescriptive about the desire to connect cookbooks to automated test frameworks and add those badges to the readme files?

**Comment by robbkidd** [comment]
In my dream of dreams for a relatively simple change to Supermarket, we would be able to query a CI build badge based on a git tag reference.

**Comment by coderanger** [comment]
So the problem with shields.io is most READMEs will (correctly) be set up to show the build status or whatever else of the branch used for development which could be confusing since supermarket groks versioned releases. Shields does allow using a git tag name for some services, and the tag name is usually related to the version, but sighhhh.

**Comment by robbkidd** [comment]
Hunh.

Supermarket v2.8.32 (tag) build status: [Build Status](https://travis-ci.org/chef/supermarket)

```
https://api.travis-ci.org/chef/supermarket.svg?tag=2.8.32
```

Substituted `branch=` with `tag=` and it appears to Just Work™.

**Comment by thommay** [comment]
The decision of the developer meeting was that @martinisoft would turn this into a quality metric and move it to the appropriate repository.

**Pull request closed without merging**
