### PR TITLE
CBGB meets twice a year.

### PR DESCRIPTION
**Pull request by nathenharvey**
Quarterly is not required.

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by ranjib** [comment]
:+1:

**Comment by philoserf** [comment]
👍

**Comment by jonlives** [comment]
👍

**Comment by evan2645** [comment]
👍

**Comment by nathenharvey** [comment]
@chef/rfc-editors this has enough votes from CBGB members to be merged.

Thanks!

**Comment by thommay** [comment]
Merged, thanks!

**Pull request merged**
