### PR TITLE
Remove IRC advocates and add Slack

### PR DESCRIPTION
**Pull request by tas50**
As a company we're not maintaining IRC anymore. Swap IRC for Slack and also add myself for GitHub.

### CODE REVIEW

**Comment by tas50** [comment]
We should probably kill off one of those

**Comment by robbkidd** [comment]
I didn't kill either off, but added a commit to update the `ADVOCATES.{toml|md}` for comparison.

**Comment by robbkidd** [comment]
Removed the list of advocates from RFC020 in favor of a link to ADVOCATES.md.

**Comment by robbkidd** [comment]
@tas50 I think this is ready for a final review.

**Pull request merged**
