### PR TITLE
RFC for PowerShell DSC integration

### PR DESCRIPTION
**Pull request by adamedx**
Use this pull request to discuss the functionality described in this RFC for Chef resources for PowerShell DSC. Feedback on functionality, usability, interfaces, or implementation details is welcome!

### CODE REVIEW

**Comment by nathenharvey** [comment]
This PR is currently on the [agenda for our next IRC developers' meeting](https://github.com/chef/chef-community-irc-meetings/blob/master/2015-03-19-agenda.md).

Please let me know if it gets merged or otherwise closed before then so that the agenda can be updated.

Thanks!

**Comment by coderanger** [comment]
The author (Adam or someone authorized by Chef to speak on his behalf) will need to confirm the release to the public domain before this can discussed.

**Comment by adamedx** [comment]
This PR pre-dates the current RFC process and concerns functionality already released in Chef 11, so I'm going to close this one.

Thanks @nathenharvey.

**Comment by adamedx** [comment]
Closing again since apparently a bot reopened it. :)

**Pull request closed without merging**
