### PR TITLE
Add author responsibility to template

### PR DESCRIPTION
**Pull request by thommay**
It is a problem that we have a lot of unfunded RFCs. We need to remind authors that they're explicitly committing to do the work to implement the RFC. @chef/rfc-editors @adamhjk

### CODE REVIEW

**Comment by coderanger** [comment]
Agree with the intent, but not in love with having that there mostly because we're just going to have remind everyone to remove it before merge (or do it ourselves).

**Comment by coderanger** [comment]
Maybe in the Specification section add something like `A detailed description of the planned implementation, which the RFC author agrees to execute.`?

**Comment by thommay** [comment]
Yeah, that might be better.

**Comment by coderanger** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by btm** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

**Pull request merged**
