### PR TITLE
Add another 'open to hugs' suggestion

### PR DESCRIPTION
**Pull request by martinb3**
Suggest we could do badge stickers for being 'open to hugs' like we had at the last ChefConf for people who are open to discussing specific topics.

### CODE REVIEW

**Comment by jjasghar** [comment]
Until the sicker RFC or that decision is made, I don't think I want to put it in hugging RFC. It'll be a great addendum, but at the time being we should take note of this, as something we can work toward.

**Comment by martinb3** [comment]
@jjasghar What's the sticker RFC? :)

**Comment by jjasghar** [comment]
Per the https://github.com/chef/chef-rfc/pull/164 we decided to only scope the RFC as just the *act* of hugging. The sticker RFC which still needs to be written will cover the badge stickers and the like.

**Comment by martinb3** [comment]
Ah! :+1: then. I'm behind the times :eyes:

**Pull request closed without merging**
