### PR TITLE
Shipping audit controls

### PR DESCRIPTION
**Pull request by thommay**

### CODE REVIEW

**Comment by chris-rock** [comment]
As discussed with @thommay:
1. we will have a audit phase in chef-client
2. we will remove the built-in audit mode, therefore the existing serverspec-based implementation will be externalized into a cookbook
3. we introduce a audit-handler to allow cookbooks to register for the audit phase. audit-handler are always executed in the audit phase and not during the converge phase
4. we should have the ability to upload the test directory with cookbooks to (chef-server), which is already covered in RFC 67 https://github.com/chef/chef-rfc/blob/master/rfc067-cookbook-segment-deprecation.md

**Comment by jtimberman** [comment]
Per discussion in today's developer meeting, the new `audit` directory will be included in the cookbook artifact that gets shipped to, e.g., Supermarket. Tools that handle the upload / sharing of cookbooks will need to know about the audit directory. As one example, `stove` has a list of [acceptable files](https://github.com/sethvargo/stove/blob/master/lib/stove/packager.rb#L10-L25) that needs to be updated, and any versions of ChefDK that ship with this feature will need to ensure their stove version is updated too.

**Comment by chris-rock** [comment]
@jtimberman I am not sure why we still need the audit directory. As discussed with @thommay (see result above) we fully opted into the AuditHandler approach instead of using a specific directory to identify a audit cookbook.

**Comment by chris-rock** [comment]
@thommay Awesome. Thank you for the update. That perfectly reflects it.

**Comment by thommay** [comment]
Approved, take it away @chef/rfc-editors

**Pull request merged**
