### PR TITLE
Subject Tagging for discourse or emailing.

### PR DESCRIPTION
**Pull request by jjasghar**
I added `tagging messages` and some `general topics` to start the discussion.

### CODE REVIEW

**Comment by adamleff** [comment]
I'm :-1: on this. We have a lot of newcomers to "the mailing list" (aka Discourse) that come to ask "new user" questions, and I would hate for their first interaction to be an over-eager member replying with the equivalent of "you're using the mailing list wrong - go read this instruction sheet for next time." It doesn't feel welcoming.

If this is an issue on which many people in the community are feeling pain, I'd suggest we look at adding additional categories to Discourse and allowing users to opt-in/out of the categories they care about. I personally don't see the value currently based on current post volume, but I'll leave that up to other people to discuss. :smile:

**Comment by thommay** [comment]
I'm with Adam on this :-1:

**Comment by jaymzh** [comment]
Agreed on the :-1: - though as with many mailing lists, if you make it a habit of doing nice subject tagging, others may follow suit. That said, I'm not opposed to forking of a separate mailing list for topics that turn out to be large-volume. One dumping ground can get very noisy.

**Comment by thommay** [comment]
The general consensus is that we don't really need to be prescriptive about tags right now, given the relatively low traffic volume through discourse.

If our community want to volunteer their time to tagging posts after the fact that would be appreciated and definitely not discouraged, though.

**Pull request closed without merging**
