### PR TITLE
Roadmap

### PR DESCRIPTION
**Pull request by btm**
Some food for thought for fulfilling parts of roadmap discussions from: https://github.com/chef/chef-rfc/pull/97

### CODE REVIEW

**Comment by nathenharvey** [comment]
:+1:

**Comment by ranjib** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Comment by jonlives** [comment]
By the powers vested in me by the state of @adamhjk, I now pronounce this RFC approved. We'll iterare on it once we get a feel for how things are working in practice. @chef/rfc-editors

**Pull request merged**
