### PR TITLE
Add Mac OS X 10.11 as a supported platform

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by coderanger** [comment]
Rather than discussing at meeting, ping @jtimberman for LT approval?

**Comment by lamont-granquist** [comment]
yeah i can't imagine there's any debate here

**Comment by thommay** [comment]
I'm :+1: , let's get @jtimberman's approval and merge.

**Comment by johnbellone** [comment]
:+1:

**Comment by jtimberman** [comment]
:+1: :shipit:

**Pull request merged**
