### PR TITLE
Register SBP prefix

### PR DESCRIPTION
**Pull request by shoekstra**

### CODE REVIEW

**Comment by shortdudey123** [comment]
Looks like there is already 6 cookbooks w/ the `sbp` prefix

**Comment by coderanger** [comment]
The existing 5:

```
sbp_emet, Matthijs Wijers mwijers
sbp_screen, Sander van Harmelen svanharmelen
sbp_mcafee, Sander van Harmelen svanharmelen
sbp_netmon, Sander van Harmelen svanharmelen
sbp_packer, Andrew Repton seth-karlo
```

Are those all coworkers or yours?

**Comment by shoekstra** [comment]
Indeed they are.

We're in the process of moving these to the sbp-cookbooks repo and I'll be creating a shared/bot account to take over ownership.

**Comment by coderanger** [comment]
:+1:

**Comment by robbkidd** [comment]
I count 15, all owned by one of: `svanharmelen, mwijers, seth-karlo, joriz`

```
sbp_baremetalsoft
sbp_chef_embedded
sbp_cloudmonkey
sbp_emet
sbp_mcafee
sbp_messageanalyzer
sbp_mremoteng
sbp_netmon
sbp_packer
sbp_safenet
sbp_screen
sbp_sysinternals
sbp_tcp_offloading
sbp_tortoisegit
sbp_treesizefree
```

**Pull request merged**
