### PR TITLE
Automatically assign a reviewer to a new PR

### PR DESCRIPTION
**Pull request by thommay**
We would like to automatically assign PRs to a reviewer on submission.

### CODE REVIEW

**Comment by jonlives** [comment]
I like this a lot. :+1: - especially :+1: on already having thought of how to detect the right maintainers in core subcomponents :p

**Comment by lamont-granquist** [comment]
:+1:

**Comment by someara** [comment]
+1

**Comment by smurawski** [comment]
I'm so :+1: on this.

**Comment by ranjib** [comment]
:+1:

**Comment by jtimberman** [comment]
:+1: :cake:

**Comment by jonlives** [comment]
This is approved, once @thommay has added a clarification about maintainers being on vacation. @chef/rfc-editors

**Comment by btm** [comment]
This is RFC043.

**Pull request merged**
